spring:
  application:
    name: start
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://laysan.com:3306/test?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      # 初始连接数
      initial-size: 5
      # 最小连接数
      min-idle: 10
      # 最大连接数
      max-active: 20
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 60000
      # 连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      # 连接在池中最大生存的时间
      max-evictable-idle-time-millis: 900000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 检测连接是否有效
      validation-query: select 1
      # 配置监控统计
      webStatFilter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
      filter:
        stat:
          enabled: true
          # 记录慢SQL
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  redis:
    host: laysan.com
    port: 6379
    database: 0
    timeout: 8s
  cache:
    type: redis

surgeon:
  cors: enable
  caching:
    default-timeout: 60s
    specs:
      dictCache:
        timeout: 20
      userCache:
        timeout: 60
        max: 500
      testCache:
        timeout: 5
        max: 10
  file:
    provider: local
    local:
      linux:
        path: /home/lise/file/
      mac:
        path: /Users/lise/file/
      windows:
        path: C:\file\
    minio:
      endpoint: http://laysan.com:9000
      accessKey: minio
      secretKey: minio@123
      bucket: ${spring.application.name}
  swagger:
    enable: true



knife4j:
  enable: true
  production: false
  base_package: com.ssyuntu.travel|com.ssyuntu.travel
  setting:
    enableSwaggerModels: true
    swaggerModelName: 请求实体对象
  info:
    title: 文旅资质评定系统
    description: 文旅资质评定系统
    service_url: http://www.ssyuntu.com
    version: 1.0
    group_name: v1
    author:
      name: Ssyuntu
      url: http://www.ssyuntu.com
      email: admin@ssyuntu.com